#
# Containers for the webfactory: see the README
# Requires: docker > 1.8.1
# 

webfact:
  container_name: webfact
  hostname: webfact 
  image: boran/drupal
  #log_driver: "syslog"    # optional
  #build: .
  #mem_limit: 500m     # optional: limit resources
  #restart: never
  restart: always
  ports:
   - "8000:80"
   - "8443:443"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - /opt/sites:/opt/sites
   # Persistence of webfact container not needed on local laptop?
   #- /opt/sites/webfact/www:/var/www/www
   #- /opt/sites/webfact/data:/data
  environment:
   - VIRTUAL_HOST=webfact.docker  # used by nginx-proxy routing
   - DRUPAL_SITE_NAME=WebFactory
   - DRUPAL_ADMIN_EMAIL=drupal@webfact.docker # adapt
   - DRUPAL_SITE_EMAIL=drupal@webfact.docker  # adapt
   # Build webfactory within the container:
   - DRUPAL_MAKE_REPO=https://github.com/Boran/webfact-make
   - DRUPAL_MAKE_DIR=webfact-make
   - DRUPAL_INSTALL_PROFILE=webfactp
   - DRUPAL_FINAL_SCRIPT=/opt/drush-make/webfact-make/scripts/final.sh
   # optional
   - WEBFACT_BACKUP=no
   - DRUPAL_SSL=yes
   # Internet access via a proxy?
   #- https_proxy=http://proxy.example.ch:80
   #- http_proxy=http://proxy.example.ch:80
   #- ftp_proxy=http://proxy.example.ch:80
   #- no_proxy=localhost,127.0.0.1,.local,.docker
  labels:
    com.example.description: "Webfactory docker UI"

##### Advanced: reverse proxy for port to container mapping #####
nginx:
  image: nginx
  container_name: nginx
  hostname: nginx
  restart: always
  ports:
   - "80:80"
   - "443:443"
  volumes:
  - /opt/sites/nginx/conf:/etc/nginx/conf.d  # adapt
  - /opt/sites/nginx/certs:/etc/nginx/certs  # adapt
  labels:
    com.example.description: "nginx reverse proxy"

nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  hostname: nginx-gen
  restart: always
  volumes_from:
  - nginx
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro
  - /opt/sites/nginx-gen/templates:/etc/docker-gen/templates # adapt
  command: -notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  labels:
    com.example.description: "nginx config generator"

