#
# Containers for the webfactory: se the README
# Requires: docker > 1.8.1
# 

nginx:
  container_name: nginx-proxy
  hostname: nginx-proxy 
  image: jwilder/nginx-proxy
  restart: always
  ports:
   - "80:80"
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock
  #environment:
   # Internet access via a proxy?
   #- https_proxy=http://proxy.example.ch:80
   #- http_proxy=http://proxy.example.ch:80
   #- ftp_proxy=http://proxy.example.ch:80
   #- no_proxy=localhost,127.0.0.1,.local,.docker
  labels:
    com.example.description: "Webfactory simple http reverse nginx proxy"

webfact:
  container_name: webfact
  hostname: webfact 
  #log_driver: "syslog"    # optional
  #build: .
  image: boran/drupal
  mem_limit: 500m     # optional: limit resources
  #restart: never
  restart: always
  ports:
   - "8000:80"
   - "8443:443"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - /opt/sites:/opt/sites
   # Persistence of webfact container not needed on local laptop?
   #- /opt/sites/webfact/www:/var/www/www
   #- /opt/sites/webfact/data:/data
  environment:
   - VIRTUAL_HOST=webfact.docker  # used by nginx-proxy routing
   - DRUPAL_SITE_NAME=WebFactory
   - DRUPAL_ADMIN_EMAIL=drupal@webfact.docker # adapt
   - DRUPAL_SITE_EMAIL=drupal@webfact.docker  # adapt
   # Build webfactory within the container:
   - DRUPAL_MAKE_REPO=https://github.com/Boran/webfact-make
   - DRUPAL_MAKE_DIR=webfact-make
   - DRUPAL_INSTALL_PROFILE=webfactp
   - DRUPAL_FINAL_SCRIPT=/opt/drush-make/webfact-make/scripts/final.sh
   # optional
   - WEBFACT_BACKUP=no
   - DRUPAL_SSL=yes
   # Internet access via a proxy?
   #- https_proxy=http://proxy.example.ch:80
   #- http_proxy=http://proxy.example.ch:80
   #- ftp_proxy=http://proxy.example.ch:80
   #- no_proxy=localhost,127.0.0.1,.local,.docker
  labels:
    com.example.description: "Webfactory docker UI"

##### Advanced: manual config required #####
#nginx:
#  image: nginx
#  container_name: nginx
#  hostname: nginx
#  restart: always
#  ports:
#   - "80:80"
#   - "443:443"
#  volumes:
#  - /opt/sites/nginx:/etc/nginx/conf.d  # adapt
#  - /root/inno-drupal/sslkeys:/etc/nginx/certs  # adapt
#  labels:
#    com.example.description: "Webfactory generic nginx"

nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  #log_driver: "syslog"    # optional
  hostname: nginx-gen
  restart: always
  volumes_from:
  - nginx
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
  - /root/inno-drupal/nginx-templates:/etc/docker-gen/templates # adapt
  - /root/inno-drupal/sslkeys:/etc/nginx/certs  # adapt
  command: -notify-sighup nginx -only-exposed -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  labels:
    com.example.description: "Webfactory nginx config generator"

